spring:
  application:
    name: employee-services  
  jpa:  
    hibernate:  
      ddl-auto: update  
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
    show-sql: true
  datasource:  
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/postgres"  
    username: postgres  
    password: root
  
# Server configuration
server:
  port: 8080 #set your port
